name: Deploy to Heroku

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ['unistudents-prod-1', 'unistudents-prod-4', 'unistudents-prod-5', 'unistudents-prod-6']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download Student-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/student-service"
          latest: true
          fileName: "student-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - name: Download eLearning-service Jar archive
        uses: robinraju/release-downloader@v1.7
        with:
          repository: "UniStudents/elearning-service"
          latest: true
          fileName: "elearning-service-full.jar"
          token: ${{ secrets.GH_TOK }}
      - run: find ./libs -name "student-*.jar" -exec cp student-service-full.jar {} \;
      - run: find ./libs -name "elearning-*.jar" -exec cp elearning-service-full.jar {} \;

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15  # This is the Heroku deployment action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ matrix.app_name }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}     
