name: Deploy to Heroku

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app_name: ['unistudents-prod-1', 'unistudents-prod-4', 'unistudents-prod-5', 'unistudents-prod-6']
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.13.15  # This is the Heroku deployment action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ matrix.app_name }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
